apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linker.fullname" . }}-secret
  labels:
    {{- include "linker.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  SESSION_SECRET: {{ .Values.sessionSecret | quote }}
  {{- if .Values.google.enabled }}
  GOOGLE_CLIENT_ID: {{ .Values.google.clientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.google.clientSecret | quote }}
  {{- end }}